apiVersion: v1
kind: Service
metadata:
  name: cloud-pod-service
  labels:
    app: test-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-app
  type: LoadBalancer