
apiVersion : apps/v1
kind: Deployment
metadata:
  name: develeap-deployment
  labels:
    app : develeap-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: develeap
  template:
    metadata:
      labels:
        project: develeap
    spec:
      containers:
        - name : my-web
          image: public.ecr.aws/x0v9s0q7/vladimir_public:latest
          ports:
            - containerPort: 80   # Port on Pod

---
apiVersion: v1
kind: Service
metadata:
  name: develeap-service
  labels:
     owner: VladimirKogan
spec:
  type: LoadBalancer
  selector:
    project: develeap
  ports:
    - name      : my-web-app-listener
      protocol  : TCP
      port      : 80
      targetPort: 80
